quarkus:
  quarkus:
    transaction-manager:
      default-transaction-timeout: 300s
  hibernate-orm:
    package: org.ged
    database:
      generation: drop-and-create

#  flyway:
#    migrate-at-start: true

  datasource:
    username: postgres
    password: postgres
    jdbc:
      max-size: 20
      min-size: 3
      url: jdbc:postgresql://0.0.0.0:5433/sistema

    db-kind: postgresql


  http:
    cors:
      ~: true
      origins: http://localhost:4200

server:
  port: 8080
  servlet:
    context-path: /ged/api/

keycloak:
  realm: sistema
  domain: localhost:9081
  adminClientId: admin-cli
  adminClientSecret: lllx08MlhGbZLpejvJ7vgbzutxO04WmX
  client: sistemaClient
  urls:
    auth: http://${keycloak.domain}
